Downcast ByteBuffer refs to Buffer before invoke limit or position
If using a Java compiler later than 1.8, but 1.8 JDK runtime, then
NoSuchMethodError will be thrown when invoking ByteBuffer limit()
or position() methods - this is due to covariant return types
introduced with Java 1.9.

See #829.

With this fix, we still support compiling on up-to-date JDK's and
using any runtime JDK from 1.6+.